use sakila;

-- List the number of films per category.

select c.name as Category, count(f.film_id) as 'Number of Films'
from category as c join film_category as f
on f.category_id = c.category_id
group by f.category_id;

-- Retrieve the store ID, city, and country for each store.

select s.store_id as 'Store ID', c.city as 'City',co.country as 'Country'
from store as s join address as a
on s.address_id = a.address_id
join city as c
on a.city_id = c.city_id
join country as co
on c.country_id = co.country_id
;

-- Calculate the total revenue generated by each store in dollars.

select s.store_id as 'Store ID',
sum(p.amount) as 'Total Revenue'
from store as s join staff as st
on s.store_id = st.store_id
join payment as p
on st.staff_id = p.staff_id
group by s.store_id
order by s.store_id;

-- Determine the average running time of films for each category.

select c.name as 'Category',
avg(f.length) as 'Average Running Time'
from category as c
join film_category as fc
on c.category_id = fc.category_id
join film as f
on fc.film_id = f.film_id
group by c.category_id, c.name
order by avg(f.length) desc;

-- Bonus:
-- Identify the film categories with the longest average running time.

SELECT c.name AS 'Category',
AVG(f.length) AS 'Average Running Time'
FROM category AS c
JOIN film_category AS fc
ON c.category_id = fc.category_id
JOIN film AS f
ON fc.film_id = f.film_id
GROUP BY c.category_id, c.name
ORDER BY AVG(f.length) DESC;

-- Display the top 10 most frequently rented movies in descending order.

SELECT f.title AS 'Film Title',
COUNT(r.rental_id) AS 'Times Rented'
FROM film AS f
JOIN inventory AS i
ON f.film_id = i.film_id
JOIN rental AS r
ON i.inventory_id = r.inventory_id
GROUP BY f.film_id, f.title
ORDER BY COUNT(r.rental_id) DESC
LIMIT 10;

-- Determine if "Academy Dinosaur" can be rented from Store 1.

SELECT f.title AS 'Film Title',
i.store_id AS 'Store ID',
i.inventory_id AS 'Inventory ID'
FROM film AS f
JOIN inventory AS i
ON f.film_id = i.film_id
WHERE f.title = 'Academy Dinosaur'
AND i.store_id = 1;

-- Provide a list of all distinct film titles, along with their availability status in the inventory. 
-- Include a column indicating whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory,
-- and this information can be obtained using a CASE statement combined with IFNULL."

SELECT DISTINCT f.title AS 'Film Title',
CASE
WHEN IFNULL(i.inventory_id, 0) = 0
THEN 'NOT available'
ELSE 'Available'
END AS 'Availability Status'
FROM film AS f
LEFT JOIN inventory AS i
ON f.film_id = i.film_id
ORDER BY f.title;
